sudo: required
services:
  - docker

before_install:
  - docker build -t xscotophilic/workflow-docker-github-travis-aws-eb -f Dockerfile .

script:
  - docker run xscotophilic/workflow-docker-github-travis-aws-eb npm run test -- --coverage
