sudo: required
services:
  - docker

before_install:
  - docker build -t xscotophilic/workflow-docker-github-travis-aws-eb -f Dockerfile.dev .

script:
  - docker run -e CI=true xscotophilic/workflow-docker-github-travis-aws-eb npm run test
